server {
    listen 80;

    # Fichiers React statiques
    location / {
        root  /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le backend K8s — toutes les routes API
    # /api/projets, /api/certifications, /api/messages, /api/auth
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass         http://backend-service:5000;
        proxy_http_version 1.1;
        proxy_set_header   Host            $host;
        proxy_set_header   X-Real-IP       $remote_addr;
        proxy_read_timeout 60s;
    }
}
